semver checking for release script

diff --git a/release b/release
--- a/release
+++ b/release
@@ -1,8 +1,19 @@
 #!/usr/bin/env bash
 
+CMD_GREP='/bin/grep'
+if [ 'Darwin' = "$(uname)" ]; then
+  type ggrep >/dev/null 2>&1
+  if [ $? -eq 0 ]; then
+    CMD_GREP="$(which ggrep)"
+  else
+    error "Must install GNU grep with 'brew install grep'"
+    exit 1
+  fi
+fi
+
 usage() {
   echo 'Usage:' >&2
-  echo "  release 'notes about the release'" >&2
+  echo "  release [--version=VERSION_OVERRIDE] 'notes about the release'" >&2
   echo "  release --version VERSION_OVERRIDE 'notes about the release'" >&2
 }
 
@@ -22,6 +33,21 @@ bump-patch() {
   echo "${jnv}.${ipv}"
 }
 
+validate-semver() {
+  if [ -z "${1}" ]; then
+    echo "Version cannot be empty!" >&2
+    return 255
+  fi
+
+  local sv="${1}"
+  gv="$(echo "${sv}" | "${CMD_GREP}" -P '^[0-9]+\.[0-9]+\.[0-9]+$')"
+  if ! [ "${gv}" = "${sv}" ]; then
+    echo "Version [${sv}] is not a semantic version!" >&2
+    return 255
+  fi
+  return 0
+}
+
 git-stuff() {
   git tag -a -m "${release_notes}" "${version}" && \
     git push --tag && \
@@ -29,22 +55,32 @@ git-stuff() {
 }
 
 
+# Options
 if [ "${1}" = '--version' ]; then
   if [ $# -ne 3 ]; then
     usage
     exit 1
   fi
   version="${2}"
+  validate-semver "${version}" || exit 1
   shift 2
+elif [ "${1:0:10}" == '--version=' ]; then
+  version="${1:10}"
+  validate-semver "${version}" || exit 1
 else
   git_version="$(git-get-latest-version)"
   version="$(bump-patch "${git_version}")"
-  if [ $? -ne 0 ]; then
+  if [ $? -ne 0 ] || [ -z "${version}" ]; then
     echo "Could not bump patch from git version [${git_version}]" >&2
     exit 1
   fi
 fi
 release_notes="${1}"
+if [ -z "${release_notes}" ]; then
+  echo "Release notes cannot be empty!" >&2
+  usage
+  exit 1
+fi
 
 # Main
 git-stuff
